/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119683-ga18b2c2696-20250524"
#endif /* AVUTIL_FFVERSION_H */
